name: add artifact links to pull request and related issues
on:
  workflow_run:
    workflows: [build html version of the ss3 user manual, Build SS3 user manual using texlive]
    types: [completed]

jobs:
  artifacts-url-comments:
    name: add artifact links to pull request and related issues job
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: add artifact links to PR and issues
        uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            prefix: Here are the artifacts from your PR.
            suffix: Have a nice day.
            format: name
            addTo: pullandissues