name: Build html for last release using texlive
on: [workflow_dispatch]
jobs:
  call-workflow:
    uses: nmfs-ost/ss3-doc/.github/workflows/build-ss3-manual-html.yml@main
    with:
    # Note: upon new releases, will need to update this ref
      ref: 'v3.30.22.1'
