name: Build documentation and deploy it to the website
on:
  push:
    branches: change-html-font
    paths:
      - '**.tex'
      - '**.Rmd'
      - 'docs/**'
  workflow_dispatch:
jobs:
  call-workflow:
    uses: nmfs-stock-synthesis/workflows/.github/workflows/deploy-ss3-docs.yml@change-html-font
